### ISSUE TITLE
Creating multiple access points in parallel fails...

### ISSUE THREAD

**Issue by mikesname** [EHRI/ehri-rest#40]
Inserting a new action at the head of the event queue consistently causes a relationship not found error when the current head-to-event link is deleted:

```
 Relationship 1638 not found
Caused by: org.neo4j.graphdb.NotFoundException: Relationship 1638 not found
    at org.neo4j.kernel.impl.core.NodeManager.getRelationshipForProxy(NodeManager.java:675)
    at org.neo4j.kernel.InternalAbstractGraphDatabase$7.lookupRelationship(InternalAbstractGraphDatabase.java:783)
    at org.neo4j.kernel.impl.core.RelationshipProxy.delete(RelationshipProxy.java:62)
    at com.tinkerpop.blueprints.impls.neo4j.Neo4jGraph.removeEdge(Neo4jGraph.java:490)
    at com.tinkerpop.frames.FramedGraph.removeEdge(FramedGraph.java:357)
    at eu.ehri.project.persistence.ActionManager.replaceAtHead(ActionManager.java:429)
    at eu.ehri.project.persistence.ActionManager.logEvent(ActionManager.java:317)
    at eu.ehri.project.persistence.ActionManager.logEvent(ActionManager.java:363)
    at eu.ehri.project.views.DescriptionViews.create(DescriptionViews.java:58)
    at eu.ehri.extension.DescriptionResource.createAccessPoint(DescriptionResource.java:139)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

This doesn't appear to be an artefact of Blueprints TX handling, since even when a TX is explicitly started it still occurs.

**Comment by mikesname** [comment]
Fixed with Neo4j 2.x and above, with its stricter index/graph TX coordination.
